| Verb        | 🗣️              | Sinhala Meaning(s)                                           | Usage                                                                                                |
| ----------- | -------------- | ------------------------------------------------------------ | ---------------------------------------------------------------------------------------------------------------- |
| pace        | /peɪs/         | සක්මන් කරනවා,<br>වේගය පිහිටුවනවා                                     | ~ adv./prep.,<br>~ something                                                                                           |
| pack        | /pæk/          | අඩුක්කරනවා,<br>තදබදව අසුරනවා                                      | ~ something (in/into something)                                                                                              |
| paint       | /peɪnt/        | සිතුවම් කරනවා,<br>සායම් ගානවා,<br>තීත්ත ගානවා                                  | ~ someone/something,<br>~ something (with something),<br>~ something + a:                                                                     |
| panic       | /ˈpænɪk/       | හදිසි බියෙන් කලබල වෙනවා/කරනවා                                        | ~ (someone)                                                                                                           |
| pant        | /pænt/         | හති දානවා                                                       |                                                                                                                  |
| paralyse    | /ˈpærəlaɪz/    | අඩපණ කරනවා,<br>අඩාල කරනවා                                       | ~ someone/something                                                                                                         |
| paraphrase  | /ˈpærəfreɪz/   | කියූ/ලියූ දෙයක් වෙනත් වචනවලින් තේරුම් කරනවා (තේරෙන භාෂාවෙන් කියනවා)                | ~ (something)                                                                                                          |
| pardon      | /ˈpɑːdn/       | සමාව දෙනවා,<br>වරදකින් නිදහස් කරනවා                                     | ~ someone/something                                                                                                         |
| park        | /pɑːk/         | (වාහනයක්) නතර කරනවා                                             | ~ something (adv./prep.)                                                                                               |
| parry       | /ˈpæri/        | ප්‍රහාරයක් වළක්වනවා                                                | ~ (something)                                                                                                          |
| participate | /pɑːˈtɪsɪpeɪt/ | සහභාගී වෙනවා                                                     | ~ (in something)                                                                                                       |
| pass        | /pɑːs/         | යමක් පසු කර යනවා,<br>සමත් වෙනවා,<br>ඉදිරියට යනවා,<br>අතින් අතට යනවා/යවනවා | ~ someone/something,<br>~ adv./prep.,<br>~ someone something,<br>~ something (to someone)                                                         |
| paste       | /peɪst/        | අලවනවා                                                        | ~ something (adv./prep.)                                                                                               |
| pat         | /pæt/          | පැතලි අතින් හෙමිහිට<br>තට්ටු කරනවා                                     | ~ something                                                                                                            |
| patch       | /pætʃ/         | අණ්ඩ දමනවා                                                     | ~ something (with something)                                                                                                 |
| patrol      | /pəˈtrəʊl/     | මුර සංචාරයේ යෙදෙනවා                                                 | ~ (something)                                                                                                          |
| pawn        | /pɔːn/         | උකස් කරනවා                                                     | ~ something                                                                                                            |
| pay\*       | /peɪ/          | ගෙවනවා etc.                                                    | ~ (something) (for something),<br>~ someone something,<br>~ (something) (to/for someone),<br>~ (someone) (for something),<br>~ someone to do something,<br>~ with something    |
| peek        | /piːk/         | (නොබැලිය යුත්තක් දිහා) හොරෙන් බලනවා                                      | ~ at someone/something,<br>~ adv./prep.                                                                                     |
| peel        | /piːl/         | පොතු අරිනවා,<br>ලෙලි අරිනවා,<br>පොතු ගැලවෙනවා                             | ~ something,<br>~ something (away/off),<br>~ (off)                                                                           |
| peep        | /piːp/         | සිදුරකින් එබී හොරෙන් බලනවා                                            | ~ at someone/something,<br>~ adv./prep.                                                                                     |
| penetrate   | /ˈpenətreɪt/   | පසාරු කරගෙන යනවා                                                 | ~ something,<br>~ into/through something                                                                                     |
| perfect     | /pəˈfekt/      | යමක් පරිපූර්ණත්වය දෙසට වැඩි දියුණු කරනවා                                 | ~ something                                                                                                            |
| perform     | /pəˈfɔːm/      | (යමක්) කරනවා,<br>(නාට්‍යයක) රඟ පානවා                                   | ~ (something),<br>~ adv./prep.                                                                                         |
| perish      | /ˈperɪʃ/       | විනාශ වෙනවා                                                      |                                                                                                                  |
| permit      | /pəˈmɪt/       | අවසර දෙනවා                                                     | ~ something,<br>~ someone to do something                                                                                         |
| persuade    | /pəˈsweɪd/     | කෙනෙක්ව<br>(යමක් කරන්නට) පොළඹවා ගන්නවා                                | ~ someone (to do something),<br>~ someone (into doing something)                                                                       |
| pet         | /pet/          | හුරතල් කරනවා                                                    | ~ someone/something                                                                                                         |
| phone       | /fəʊn/         | දුරකතනයෙන් අමතනවා                                                | ~ someone/something                                                                                                         |
| pick        | /pɪk/          | තෝරාගන්නවා,<br>(දත්/නහය) හාරනවා,<br>නෙළා ගන්නවා,<br>ඇහිඳිනවා                        | ~ someone/something,<br>~ something up                                                                                            |
| pierce      | /pɪəs/         | විදිනවා,<br>පසාරු කරගෙන යනවා                                        | ~ something,<br>~ (though) something                                                                                         |
| place       | /paɪl/         | එක උඩ එක තියනවා/ගොඩගහනවා                                         | ~ something (up),<br>~ B on(to) A,<br>~ adv./prep.                                                                     |
| plan        | /pleɪs/        | (පරෙස්සමින්) කිසියම් තැනකින් තබනවා                                      | ~ (someone) (adv./prep.)                                                                                              |
| plant       | /plɑːnt/       | පැළ කරනවා                                                      | ~ something                                                                                                            |
| play        | /pleɪ/         | සෙල්ලම් කරනවා,<br>වාදනය කරනවා,<br>රඟ දක්වනවා                               | ~ (something)                                                                                                          |
| plead       | /pliːd/        | ආයාචනා කරනවා                                                    | ~ (with someone) (to do something),<br>~ (with someone) (for something)                                                                |
| please      | /pliːz/        | සතුටු කරනවා                                                     | ~ (someone) (to do something)                                                                                               |
| point       | /pɔɪnt/        | (ඇඟිල්ල/තුවක්කුව ආදිය) දික් කරනවා/එල්ල කරනවා                            | ~ (at/to/towards someone/something),<br>~ (something) at someone/something                                                                   |
| poison      | /ˈpɔɪzn/       | වස දෙනවා,<br>වස දානවා                                            | ~ someone,<br>~ something                                                                                                   |
| pollute     | /pəˈluːt/      | යම් දෙයක් දූෂ්‍ය කරනවා/අපිරිසිදු කරනවා                                   | ~ something (by/with something)                                                                                              |
| portray     | /pɔːˈtreɪ/     | විචිත්‍රව විස්තර කරනවා                                              | ~ someone/something (as something)                                                                                                |
| possess     | /pəˈzes/       | අයිතිව තියෙනවා,<br>අයත් කරගෙන ඉන්නවා                                  | ~ something                                                                                                            |
| post        | /pəʊst/        | තැපැල් කරනවා,<br>දැනගැනීම පිණිස ප්‍රසිද්ධ කරනවා etc.                          | ~ someone something,<br>~ something (off) (to someone),<br>~ something (adv./prep.)                                                          |
| pour        | /pɔː(r)/       | වැක්කෙරෙනවා/<br>වක්කරනවා                                            | ~ (something) (adv./prep.),<br>~ something (out),<br>~ someone something,<br>~ something for someone                                               |
| practise    | /ˈpræktɪs/     | පුරුදු පුහුණු වෙනවා,<br>ක්‍රියාවෙහි යොදවනවා                                     | ~ something,<br>~ (for something),<br>~ doing something,<br>~ (something) on someone/something                                                      |
| praise      | /preɪz/        | වර්ණනා කරනවා,<br>ප්‍රශංසා කරනවා                                      | ~ someone/something (for something),<br>~ someone/something (for doing something),<br>~ someone/something (as something)                                            |
| pray        | /preɪ/         | යාඥා කරනවා,<br>යදිනවා                                             | ~ for someone/something,<br>~ to someone (for someone/something)                                                                            |
| predict     | /prɪˈdɪkt/     | අනාවැකි පල කරනවා,<br>වෙන දේ කලින් කියනවා                                  | ~ something,<br>~ that,<br>~ wh-                                                                                       |
| prefer      | /prɪˈfɜː(r)/   | වැඩිපුර කැමතියි                                                    | ~ someone/something,<br>~ someone/something + a:,<br>~ to do something,<br>~ doing something,<br>~ that,<br>~ A to B                               |
| prepare     | /prɪˈpeə(r)/   | සූදානම් වෙනවා,<br>සූදානම් කරනවා                                       | ~ (someone/something) (for someone/something),<br>~ to do something                                                                          |
| prescribe   | /prɪˈskraɪb/   | (පොතක්/බෙහෙතක්) නියම කරනවා                                          | ~ something,<br>~ (someone) something (for something),<br>~ that,<br>~ wh-                                                              |
| present     | /prɪˈzent/     | ඉදිරිපත් කරනවා,<br>ගෙනහැර දක්වනවා,<br>තෑගි කරනවා                        | ~ something (to someone),<br>~ someone with something,<br>~ someone/something (as someone/something)                                                         |
| preserve    | /prɪˈzɜːv/     | යම් දෙයක තත්වය ආරක්ෂා කරගන්නවා,<br>කෑම කල් තබා ගන්නවා                       | ~ something                                                                                                            |
| press       | /pres/         | තද වෙනවා/කරනවා,<br>මිරිකනවා,<br>පීඩනයක් යොදනවා                            | ~ (someone/something) (against someone/something),<br>~ something together,<br>~ something to something                                                  |
| presume     | /prɪˈzjuːm/    | සත්‍ය යැයි සිතනවා,<br>අනුමාන කරනවා                                       | ~ (that),<br>~ something,<br>~ someone/something + a:,<br>~ someone/something to be someone/something,<br>~ someone/something to have done something                     |
| pretend     | /prɪˈtend/     | යම් දෙයක් බොරුවට අඟවනවා                                            | ~ (to someone) (that),<br>~ to be/do/have something,<br>~ something                                                               |
| prevent     | /prɪˈvent/     | වළක්වනවා                                                       | ~ someone/something (doing something),<br>~ someone/something (from doing something)                                                               |
| price       | /praɪs/        | මිල නියම කරනවා                                                  | ~ something at something,<br>~ something (up),<br>~ something (adv./prep.)                                                               |
| print       | /prɪnt/        | මුද්‍රණය කරනවා                                                   | ~ something                                                                                                            |
| proceed     | /prəˈsiːd/     | ඉදිරියට (කරගෙන) යනවා                                             | ~ (with something),<br>~ to do something,<br>~ adv./prep.                                                                    |
| process     | /ˈprəʊses/     | සකස් කරනවා                                                     | ~ something                                                                                                            |
| produce     | /prəˈdjuːs/    | නිෂ්පාදනය කරනවා,<br>ඉදිරිපත් කරනවා                                      | ~ something                                                                                                            |
| profit      | /ˈprɒfɪt/      | ලාභ ලබනවා                                                      | ~ (on something),<br>~ (from something)                                                                                      |
| promise     | /ˈprɒmɪs/      | පොරොන්දු වෙනවා                                                     | ~ to do something,<br>~ something,<br>~ (someone) that,<br>~ someone something,<br>~ something (to someone)                                             |
| promote     | /prəˈməʊt/     | උසස් කරනවා,<br>අනුබල දෙනවා,<br>ප්‍රවර්ධනය කරනවා                       | ~ someone (from something) (to something),<br>~ something,<br>~ something (as something)                                                            |
| prompt      | /prɒmpt/       | පොළඹවනවා,<br>උනන්දු කරවනවා                                        | ~ someone to do something                                                                                                   |
| pronounce   | /prəˈnaʊns/    | උච්චාරණය කරනවා,<br>තීන්දුවක් දෙනවා,<br>නිල වශයෙන් ප්‍රකාශයට පත් කරනවා            | ~ something,<br>~ someone/something + n:/a:,<br>~ someone/something to be/have,<br>~ that                                                    |
| propose     | /prəˈpəʊz/     | යෝජනා කරනවා                                                     | ~ something,<br>~ that,<br>~ to do something,<br>~ doing something,<br>~ to someone,<br>~ something (to someone),<br>~ someone (for/as something)             |
| protect     | /prəˈtekt/     | ආරක්ෂා කරනවා,<br>ආරක්ෂාව සපයනවා,<br>ආරක්ෂා වෙනවා                             | ~ (someone/something) (from/against something)                                                                                    |
| protest     | /prəˈtest/     | විරුද්ධත්වය ප්‍රකාශ කරනවා,<br>විරෝධය පානවා                                  | ~ (about/against/at something),<br>~ that                                                                              |
| prove       | /pruːv/        | ඔප්පු කරනවා,<br>තහවුරු කරනවා,<br>ප්‍රත්‍යක්ෂ කරනවා                             | ~ something (to someone),<br>~ that,<br>~ wh-,<br>~ someone/something + a:                                                             |
| provide     | /prəˈvaɪd/     | සපයනවා,<br>සලසනවා,<br>ලබා දෙනවා                                      | ~ something (to/for someone),<br>~ someone with something                                                                              |
| provoke     | /prəˈvəʊk/     | ප්‍රකෝප කරනවා,<br>කුලප්පු කරනවා                                      | ~ something,<br>~ someone (into something),<br>~ someone (into doing something),<br>~ someone (to do something)                                         |
| publish     | /ˈpʌblɪʃ/      | (පොතක් ආදිය) ප්‍රකාශයට පත් කරනවා                                     | ~ something                                                                                                            |
| pull        | /pʊl/          | අදිනවා                                                         | ~ (something),<br>~ (at/on something),<br>~ (ab/something) (adv./prep.)                                                            |
| punch       | /pʌntʃ/        | මිටින් පහර දෙනවා,<br>හිල් කරනවා                                      | ~ someone/something (on something),<br>~ something (in/through something)                                                                     |
| punish      | /ˈpʌnɪʃ/       | දඬුවම් කරනවා                                                    | ~ someone (for something),<br>~ someone (for doing something),<br>~ someone (by/with something)                                                   |
| purchase    | /ˈpɜːtʃəs/     | මිලදී ගන්නවා                                                     | ~ something (from someone)                                                                                                  |
| pursue      | /pəˈsjuː/      | ලුහු බැඳ යනවා                                                    | ~ someone/something                                                                                                         |
| push        | /pʊʃ/          | තල්ලු කරනවා,<br>තදින් ඉල්ලා සිටිනවා,<br>ප්‍රමාණය ඉක්මවා වෙහෙසනවා                  | ~ (something),<br>~ at something,<br>~ someone/something + adv./prep.,<br>~ something + a:,<br>~ someone (into something/doing something),<br>~ someone (to do something) |
| put\*       | /pʊt/          | දානවා,<br>තබනවා,<br>යොමු කරනවා,<br>ඉදිරිපත් කරනවා etc.                    | ~ something (adv./prep.)                                                                                               |